# Artificial Neural Network

### Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import warnings

2022-03-07 16:55:51.269612: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-07 16:55:51.269633: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
tf.__version__

'2.6.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

### Dataset checks

In [4]:
# Dimension of dataset
dataset.shape

(9568, 5)

In [5]:
# Dataset info
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB


In [6]:
# Dataset summary
dataset.describe()

AT            V           AP           RH           PE
count  9568.000000  9568.000000  9568.000000  9568.000000  9568.000000
mean     19.651231    54.305804  1013.259078    73.308978   454.365009
std       7.452473    12.707893     5.938784    14.600269    17.066995
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.510000    41.740000  1009.100000    63.327500   439.750000
50%      20.345000    52.080000  1012.940000    74.975000   451.550000
75%      25.720000    66.540000  1017.260000    84.830000   468.430000
max      37.110000    81.560000  1033.300000   100.160000   495.760000

### Splitting the dataset into the Training set and Test set

In [7]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [9]:
ann = tf.keras.models.Sequential()

2022-03-07 16:55:55.396127: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-03-07 16:55:55.396153: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (bdwumah74-Alienware): /proc/driver/nvidia/version does not exist
2022-03-07 16:55:55.396450: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


### Adding the input layer and the first hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

### Adding the second hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

### Adding the output layer

In [12]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [13]:
ann.compile(optimizer='adam', loss= 'mean_squared_error')

### Training the ANN model on the Training set

In [14]:
ann.fit(X_train, y_train, batch_size=32, epochs=200)

2022-03-07 16:55:55.792777: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/200
240/240 [==============================] - 0s 736us/step - loss: 165105.2344
Epoch 2/200
240/240 [==============================] - 0s 798us/step - loss: 1933.2551
Epoch 3/200
240/240 [==============================] - 0s 803us/step - loss: 154.7609
Epoch 4/200
240/240 [==============================] - 0s 805us/step - loss: 151.6079
Epoch 5/200
240/240 [==============================] - 0s 798us/step - loss: 147.9425
Epoch 6/200
240/240 [==============================] - 0s 783us/step - loss: 143.8431
Epoch 7/200
240/240 [==============================] - 0s 783us/step - loss: 139.2336
Epoch 8/200
240/240 [==============================] - 0s 781us/step - loss: 134.4087
Epoch 9/200
240/240 [==============================] - 0s 802us/step - loss: 128.8198
Epoch 10/200
240/240 [==============================] - 0s 824us/step - loss: 123.1036
Epoch 11/200
240/240 [==============================] - 0s 831us/step - loss: 117.1507
Epoch 12/200
240/240 [==========================

240/240 [==============================] - 0s 742us/step - loss: 26.6565
Epoch 97/200
240/240 [==============================] - 0s 940us/step - loss: 26.7163
Epoch 98/200
240/240 [==============================] - 0s 989us/step - loss: 26.6669
Epoch 99/200
240/240 [==============================] - 0s 871us/step - loss: 26.5523
Epoch 100/200
240/240 [==============================] - 0s 749us/step - loss: 26.9256
Epoch 101/200
240/240 [==============================] - 0s 948us/step - loss: 26.6220
Epoch 102/200
240/240 [==============================] - 0s 794us/step - loss: 26.7942
Epoch 103/200
240/240 [==============================] - 0s 776us/step - loss: 27.0176
Epoch 104/200
240/240 [==============================] - 0s 779us/step - loss: 26.2837
Epoch 105/200
240/240 [==============================] - 0s 766us/step - loss: 26.9687
Epoch 106/200
240/240 [==============================] - 0s 859us/step - loss: 26.3349
Epoch 107/200
240/240 [==============================] - 0s 

240/240 [==============================] - 0s 790us/step - loss: 26.6125
Epoch 191/200
240/240 [==============================] - 0s 739us/step - loss: 26.5554
Epoch 192/200
240/240 [==============================] - 0s 798us/step - loss: 26.7267
Epoch 193/200
240/240 [==============================] - 0s 789us/step - loss: 26.9452
Epoch 194/200
240/240 [==============================] - 0s 774us/step - loss: 26.7047
Epoch 195/200
240/240 [==============================] - 0s 797us/step - loss: 26.3372
Epoch 196/200
240/240 [==============================] - 0s 785us/step - loss: 26.4044
Epoch 197/200
240/240 [==============================] - 0s 795us/step - loss: 26.7438
Epoch 198/200
240/240 [==============================] - 0s 794us/step - loss: 26.8880
Epoch 199/200
240/240 [==============================] - 0s 807us/step - loss: 26.6432
Epoch 200/200
240/240 [==============================] - 0s 913us/step - loss: 26.4218


### Predicting the results of the Test set

In [19]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)), 1))

[[431.94 431.23]
 [462.98 460.01]
 [466.47 461.14]
 ...
 [473.74 473.26]
 [440.44 438.  ]
 [459.7  463.28]]


In [24]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9146534730828172